### ISSUE TITLE
Rule `//fs_image/compiler/test_images:create_ops-from-dir` fails to build

### ISSUE THREAD

**Issue by zeroxoneb** [facebookincubator/antlir#20]
Use the branch `oss_snapshot` (where a working build appliance exists).  The target fails with the following stack trace:

```
Building: finished in 1.7 sec (100%) 56/56 jobs, 1 updated
  Total time: 3.0 sec
Command failed with exit code 1.

command: [/bin/bash, -e, /home/ls/work/fs_image/buck-out/tmp/genrule-4304085449718242770.sh]

stderr: + binary_path=(/usr/bin/python3 /home/ls/work/fs_image/buck-out/gen/fs_image/subvolume-version.pex)
++ /usr/bin/python3 /home/ls/work/fs_image/buck-out/gen/fs_image/subvolume-version.pex
+ subvolume_ver=JQ6eCm4.H80.-oc
+ subvolume_wrapper_dir=create_ops-from-dir:JQ6eCm4.H80.-oc
+ mkdir /home/ls/work/fs_image/buck-out/bin/fs_image/compiler/test_images/create_ops-from-dir__/out
+ echo '{}'
+ /usr/bin/python3 /home/ls/work/fs_image/buck-out/gen/fs_image/layer-mount-config.pex //fs_image/compiler/test_images:create_ops-from-dir
+ layer_json=/home/ls/work/fs_image/buck-out/bin/fs_image/compiler/test_images/create_ops-from-dir__/out/layer.json
++ readlink -f /home/ls/work/fs_image/buck-out/gen/../../buck-out/.volume-refcount-hardlinks/
+ refcounts_dir=/home/ls/work/fs_image/buck-out/.volume-refcount-hardlinks
+ /usr/bin/python3 /home/ls/work/fs_image/buck-out/gen/fs_image/subvolume-garbage-collector.pex --refcounts-dir /home/ls/work/fs_image/buck-out/.volume-refcount-hardlinks --subvolumes-dir /home/ls/work/fs_image/buck-image-out/volume/targets --new-subvolume-wrapper-dir create_ops-from-dir:JQ6eCm4.H80.-oc --new-subvolume-json /home/ls/work/fs_image/buck-out/bin/fs_image/compiler/test_images/create_ops-from-dir__/out/layer.json
Deleting create_ops-from-dir:JQ6dx8Q.GnY.fY7U since its refcount has 1 links
Delete subvolume (no-commit): '/home/ls/work/fs_image/buck-image-out/volume/targets/create_ops-from-dir:JQ6dx8Q.GnY.fY7U/create_ops'
+ /usr/bin/python3 -Es /home/ls/work/fs_image/buck-out/gen/fs_image/compiler.pex --artifacts-may-require-repo --subvolumes-dir /home/ls/work/fs_image/buck-image-out/volume/targets --subvolume-rel-path create_ops-from-dir:JQ6eCm4.H80.-oc/create_ops --build-appliance-json /home/ls/work/fs_image/buck-out/gen/appliance/build_appliance/layer/layer.json --rpm-installer dnf --allowed-host-mount-target=//appliance:host_build_appliance --child-layer-target //fs_image/compiler/test_images:create_ops-from-dir --child-feature-json /dev/fd/62 --child-dependencies //fs_image/compiler/test_images:create_ops-dir /home/ls/work/fs_image/buck-out/gen/fs_image/compiler/test_images/create_ops-dir/create_opscreate_ops-dir
++ echo '{"features":[{"receive_sendstreams":[{"source":{"content_hash":null,"generator":null,"generator_args":[],"layer":null,"path":"sendstream","source":{"__BUCK_TARGET":"//fs_image/compiler/test_images:create_ops-dir"}}}],"target":"//fs_image/compiler/test_images:create_ops-from-dir"}],"target":"//fs_image/compiler/test_images:create_ops-from-dir"}'
At subvol create_ops
ERROR: lsetxattr hello security.selinux=user_u:object_r:base_t failed: Invalid argument
Traceback (most recent call last):
  File "<string>", line 37, in <module>
  File "<string>", line 35, in __run
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ls/work/fs_image/buck-out/gen/fs_image/compiler#link-tree/fs_image/compiler/compiler.py", line 197, in <module>
    build_image(args).to_json_file(sys.stdout)
  File "/home/ls/work/fs_image/buck-out/gen/fs_image/compiler#link-tree/fs_image/compiler/compiler.py", line 167, in build_image
    builder(subvol)
  File "/home/ls/work/fs_image/buck-out/gen/fs_image/compiler#link-tree/fs_image/compiler/items/make_subvol.py", line 85, in builder
    pass
  File "/usr/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/ls/work/fs_image/buck-out/gen/fs_image/compiler#link-tree/fs_image/subvol_utils.py", line 715, in receive
    yield
  File "/usr/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/ls/work/fs_image/buck-out/gen/fs_image/compiler#link-tree/fs_image/subvol_utils.py", line 222, in popen_as_root
    check_popen_returncode(pr)
  File "/home/ls/work/fs_image/buck-out/gen/fs_image/compiler#link-tree/fs_image/common.py", line 73, in check_popen_returncode
    returncode=proc.returncode, cmd=proc.args,
subprocess.CalledProcessError: Command '['sudo', 'TMP=', '--', 'btrfs', 'receive', b'/proc/8151/fd/6']' returned non-zero exit status 1.

    When running <genrule>.
    When building rule //fs_image/compiler/test_images:create_ops-from-dir.
```

**Comment by vmagro** [comment]
This is very old, almost all targets should build in the proper environment now
